version: '3.8'

services:
  mk-addrlist-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8080"
    volumes:
      - ./config/config.yaml:/etc/mk-addrlist-generator/config.yaml
      - ./lists:/etc/mikrotik/lists
    restart: unless-stopped